name: Sync
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push
        run: |
                git remote add codeberg https://nekoside:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/nekoside/.profile.git
                git push codeberg --all --force
                git push codeberg --tags --force